# Generated by Django 5.2 on 2025-04-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('good', 'Bueno'), ('fair', 'Regular'), ('poor', 'Malo')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('acquisition_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.book')),
            ],
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('acquisition_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('book_copy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.bookcopy')),
            ],
        ),
    ]
